### ISSUE TITLE
Call for maintainers

### ISSUE THREAD

**Issue by oporkka** [scala-jsonapi/scala-jsonapi#96]
Hi everyone,

Zalando is not using this library anymore, and therefore it has been moved to its own Github organization. It would be good to find at least two maintainers from the current user base of the library to continue the work.

I think the near future projects would be to release version 1.0 with new jar structure (see #64, pretty much ready), and find out new package names for the project. After that release it would be a lot easier to start adding support for e.g. new Play and Scala versions.

I'll tag here people from latest pull requests. Please tell what you think. @alanwguo @emanresusername @texvex @zmeda

**Comment by emanresusername** [comment]
We're actually in a similar situation, it's unclear if/how much we'll be using jsonapi in the future. For the near/medium term though we have [a fork targeting scala 2.12 and the circe module](https://github.com/RavelLaw/scala-jsonapi/tree/2.12-circe) that we will be using while we nail down our direction going forward. 
It doesn't cleanly patch into #64, but maybe there could be some helpful cross-pollination there?

**Comment by nkgm** [comment]
Feels like jsonapi is losing traction lately. Mind sharing any insights on the why, or what you're replacing it with?

**Comment by zmeda** [comment]
@oporkka Thanks for taking care of that. As a matter of fact we are using the library. Nevertheless it is not advised to use it inside Zalando for new services. I'll focus on bringing it to version 1.0 since it will help me and my pet projects.

@nkgm I have impression that people are moving away from REST in general (to grpc and others). In the REST world using non-jsonapi structures feels like more freedom and less overhead. Also one of main concerns about jsonapi is that is not back and forth compatible with non-jsonapi (you have to (un)wrap all the attributes in `data` path - we always ended up with the question WHY?).

This is my 5 cents on that. :)

**Comment by franklinchou** [comment]
@zmeda It seems as though this library has been quiet for some time. I do still find myself using the features in `scala-jsonapi` from time to time and, as of this writing, there is a fairly recent PR by @yvoderatskyi [here](https://github.com/scala-jsonapi/scala-jsonapi/pull/97). If there aren't any objections, perhaps @yvoderatskyi and I could take over the role of maintaining this project?

**Comment by oporkka** [comment]
@franklinchou I added you now.

**Comment by yvoderatskyi** [comment]
@oporkka @franklinchou could you include me as well?

**Comment by oporkka** [comment]
@yvoderatskyi done!
